CREATE DATABASE sqoop_sample;

\c sqoop_sample;

CREATE TABLE SALES
(
  SALES_ID INTEGER NOT NULL,
  SHOP_CODE TEXT NOT NULL,
  SALES_DATE DATE NOT NULL,
  REGISTER_DATE TIMESTAMP NOT NULL,
  PRIMARY KEY (SALES_ID)
);

CREATE TABLE SALES_DETAIL
(
  SALES_ID INTEGER NOT NULL,
  DETAIL_ID INTEGER NOT NULL,
  ITEM_CODE TEXT NOT NULL,
  UNIT_PRICE INTEGER NOT NULL,
  QUANTITY INTEGER NOT NULL,
  REGISTER_DATE TIMESTAMP NOT NULL,
  PRIMARY KEY (SALES_ID, DETAIL_ID)
);

COPY SALES FROM '/tmp/sqoop_training/sqoop_sample/daily-sales.tsv';
COPY SALES FROM '/tmp/sqoop_training/sqoop_sample/daily-sales_detail.tsv';
